DROP TABLE IF EXISTS "product";
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "order";
DROP SEQUENCE IF EXISTS "product_id_seq";
DROP SEQUENCE IF EXISTS "user_id_seq";
DROP SEQUENCE IF EXISTS "order_id_seq";